# Render Configuration for Real Estate Dashboard
# Developed by Maksim Kitikov - Upside Analytics

services:
  - type: web
    name: realestate-dashboard
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 0 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        sync: false  # Set this manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true
    branch: main
